POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "This is a blog post",
  "author": "Hamilton",
  "url": "http:google.com",
  "likes": 1
}

###

GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "rmt",
    "name": "Lukas Lundin",
    "password": "salainen"
}

###
GET http://localhost:3003/api/users