POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "This is another blog",
  "author": "Donald E",
  "url": "http:google.com",
  "likes": 3
}

###

GET http://localhost:3003/api/blogs