POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1a2FzZWR2IiwiaWQiOiI2MGZhYWVlNDcxZWFhMzQwODY0YzZmYjciLCJpYXQiOjE2MjcwNDUwMTl9.rqS1CL6gNd4l1KYLN3_Ginjeuq4Sju7uWPLdbmEt58o

{
  "title": "Blog to delete",
  "author": "Lyyke",
  "url": "http:google.com",
  "likes": 1
}

### Delete with right user

DELETE http://localhost:3003/api/blogs/60fabce2bdd8087eb3bded8d
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1a2FzZWR2IiwiaWQiOiI2MGZhYWVlNDcxZWFhMzQwODY0YzZmYjciLCJpYXQiOjE2MjcwNDUwMTl9.rqS1CL6gNd4l1KYLN3_Ginjeuq4Sju7uWPLdbmEt58o

### Delete with wrong user


DELETE http://localhost:3003/api/blogs/60faaf1771eaa340864c6fce
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwZmE4Njc2N2U1NDlhMDY1YjNlZjRjZSIsImlhdCI6MTYyNzAzOTM0MX0.7GUUlVFugR4xRI0x06EETwovweCM5zT_kLvV3wmuf-0

###

GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "lukasedv",
    "name": "Lukas Lundin",
    "password": "salainen"
}

###
GET http://localhost:3003/api/users

### 

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "lukasedv",
  "password": "salainen"
}

### 

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "sekret"
}
